services:

  # =====================
  # Kafka (KRaft - NO ZooKeeper)
  # =====================
  kafka:
    image: docker.arvancloud.ir/apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

  # =====================
  # Kafka UI
  # =====================
  kafka-ui:
    image: docker.arvancloud.ir/kafbat/kafka-ui:v1.4.2
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # =====================
  # Spark
  # =====================
  spark-master:
      image: docker.arvancloud.ir/spark:3.5.7-java17-python3
      container_name: spark-master
      command: >
        /opt/spark/bin/spark-class
        org.apache.spark.deploy.master.Master
      environment:
        - SPARK_MODE=master
      ports:
        - "7077:7077"
        - "8081:8080"

  spark-worker:
      image: docker.arvancloud.ir/spark:3.5.7-java17-python3
      container_name: spark-worker
      depends_on:
        - spark-master
      command: >
        /opt/spark/bin/spark-class
        org.apache.spark.deploy.worker.Worker
        spark://spark-master:7077
      environment:
        - SPARK_MODE=worker
      ports:
        - "8082:8080"


  # =====================
  # Storage
  # =====================
  postgres:
    image: docker.arvancloud.ir/postgres:15
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: streaming
      POSTGRES_USER: streaming
      POSTGRES_PASSWORD: streaming
    volumes:
      - pg_data:/var/lib/postgresql/data

  # =====================
  # Monitoring
  # =====================
  prometheus:
    image: docker.arvancloud.ir/prom/prometheus:v3.9.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.arvancloud.ir/grafana/grafana:12.3.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  kafka_data:
  pg_data:
